### ISSUE TITLE
General cleanup checklist

### ISSUE THREAD

**Issue by Godley** [Godley/Music-Library#296]
- do a general clean and refactor of drawing objective. 
  - [x] aim to remove all global variables from the parser
  - [x] make some demo scripts
  - [x] possibly create a separate repo
  - [x] submit it to pypi
- [ ] general clean of other objectives
- [ ] fix UI problems + find poppler for windows
- [ ] upgrade UIs to use PyQt5
